name: AML Mod Compiler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository...
      uses: actions/checkout@v3
        
    - name: Setup SSH keys...
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH }}

    - name: Download AndroidModLoader`s mod template...
      uses: wei/wget@v1
      with:
        args: -O ./AML_src.zip https://github.com/RusJJ/AndroidModLoader/archive/refs/heads/main.zip

    - name: Install AndroidModLoader`s mod template...
      run: |
        unzip ./AML_src.zip
        mv ./AndroidModLoader-main/mod ./mod
          
    - name: Get GTA:SA structures file (private)...
      run: |
        git clone ssh://git@github.com/RusJJ/GTASAAndroid_Structs.git ./structs
        mv ./structs/* ./

    - name: Install Android NDK (r24)...
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r24
        local-cache: true

    - name: Build the code...
      run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

    - name: Upload the mod!
      uses: actions/upload-artifact@v3
      with:
        name: compiled-mod.zip
        path: ./libs
